/* Browser-side integration check of the built site, including MathJax startup.
 * Run only from the local harness generated by build_math_audit.py.
 */
(async () => {
  const pages = await (await fetch('inventory.json')).json();
  const frame = document.querySelector('#frame');
  const results = [];
  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
  const timeout = (promise, ms) => Promise.race([
    promise, new Promise((_, reject) => setTimeout(() => reject(new Error('render timeout')), ms))
  ]);
  for (const width of [1280, 390]) {
    frame.style.width = width + 'px';
    for (const page of pages) {
      document.querySelector('#status').textContent = `${results.length}/${pages.length * 2} · ${width}px · ${page.path}`;
      const row = {...page, width, errors: [], raw: [], overflow: []};
      try {
        await timeout(new Promise(resolve => {
          frame.onload = resolve;
          frame.src = 'site/' + page.path;
        }), 30000);
        const win = frame.contentWindow;
        const doc = frame.contentDocument;
        const started = Date.now();
        while (page.expected && !win.MathJax?.startup?.promise) {
          if (Date.now() - started > 20000) throw new Error('MathJax failed to initialize');
          await sleep(50);
        }
        if (win.MathJax?.startup?.promise) await timeout(win.MathJax.startup.promise, 20000);
        await timeout(doc.fonts.ready, 10000);
        await sleep(100);
        const blocks = [...doc.querySelectorAll('.arithmatex')];
        row.blocks = blocks.length;
        row.rendered = blocks.filter(b => b.querySelector('mjx-container')).length;
        row.containers = blocks.reduce((n, b) => n + b.querySelectorAll('mjx-container').length, 0);
        blocks.forEach((block, index) => {
          const containers = block.querySelectorAll('mjx-container');
          if (containers.length !== 1) row.errors.push({index, kind:'container-count', count:containers.length, text:block.textContent.slice(0,180)});
          for (const err of block.querySelectorAll('mjx-merror, [data-mjx-error], mjx-mtext[style*="red"]')) {
            row.errors.push({index, kind:'tex-error', message:err.getAttribute('data-mjx-error') || err.textContent});
          }
          const box = block.getBoundingClientRect();
          let scrollable = false;
          for (let node = block; node && node !== doc.body; node = node.parentElement) {
            if (['auto', 'scroll'].includes(win.getComputedStyle(node).overflowX)) scrollable = true;
          }
          if (box.right > width + 2 && !scrollable) {
            row.overflow.push({index, right:Math.round(box.right), text:block.textContent.slice(0,100)});
          }
        });
        if (row.blocks !== page.expected) row.errors.push({kind:'inventory-mismatch'});
        const article = doc.querySelector('article')?.cloneNode(true);
        if (article) {
          article.querySelectorAll('.arithmatex,code,pre,script,style,svg,math,.mermaid').forEach(n=>n.remove());
          const walker = doc.createTreeWalker(article, 4);
          while (walker.nextNode()) {
            const text = walker.currentNode.textContent;
            if (/\$[^$\n]{1,200}\$|\\\(|\\\[|\\(?:frac|mathbb|mathcal|begin|theta|sum)\b/.test(text)) row.raw.push(text.trim().slice(0,250));
          }
        }
      } catch (error) { row.errors.push({kind:'runtime', message:String(error)}); }
      results.push(row);
      const problems = results.filter(r=>r.errors.length || r.raw.length || r.overflow.length);
      document.querySelector('#summary').textContent = JSON.stringify({completed:results.length,total:pages.length*2,problemPages:problems.length},null,2);
      document.querySelector('#problems').textContent = JSON.stringify(problems,null,2);
      document.querySelector('#results').textContent = JSON.stringify(results);
    }
  }
  document.querySelector('#status').textContent = '完成';
})();
